import Foundation
@testable import Contour

/// Deterministically generated, PR-shaped fixtures for `BenchTests` (issue #60): "Contour's
/// own latency on a fixture corpus," independent of any real GitHub PR so the numbers are
/// reproducible from one CI run to the next. Diffs and file contents come from a seeded
/// PRNG rather than being committed as large files — `large` alone would otherwise mean
/// tens of thousands of lines checked into the repo.
enum BenchCorpus: String, CaseIterable {
    case small, medium, large

    /// Ordinary changed files. `large` also gets one oversized file (`oversizedFileLines`)
    /// — the "one very large single file" shape DESIGN.md §14 calls out as the thing that
    /// stresses truncation and per-file work hardest.
    var fileCount: Int {
        switch self {
        case .small: return 3
        case .medium: return 40
        case .large: return 300
        }
    }

    /// Diff lines contributed by each ordinary changed file.
    var linesPerFile: Int {
        switch self {
        case .small: return 20
        case .medium: return 60
        case .large: return 120
        }
    }

    /// Extra lines in one additional, oversized file, so `large`'s diff totals tens of
    /// thousands of lines the way a generated-code or vendored-file PR would. Zero for the
    /// smaller corpora, which stay small on purpose.
    var oversizedFileLines: Int {
        switch self {
        case .small, .medium: return 0
        case .large: return 30_000
        }
    }
}

/// One materialized fixture: the `RawPRContext` bench mode feeds the pipeline, plus a real
/// on-disk checkout shaped like what `RepoContextService.checkout` produces — so
/// `CodeRefVerifier`'s file reads and the context-file write do real, size-scaled I/O
/// rather than being no-ops. The caller owns `rootDir` and must remove it when done.
struct BenchFixture {
    var context: RawPRContext
    var checkout: RepoCheckout
    var rootDir: URL
}

enum BenchFixtures {

    /// A tiny seeded PRNG (SplitMix64) so every corpus is byte-for-byte the same on every
    /// run and every machine — no `Int.random`, no timestamp-seeded state, so a slowdown
    /// measured today reproduces tomorrow.
    private struct SplitMix64: RandomNumberGenerator {
        var state: UInt64
        mutating func next() -> UInt64 {
            state &+= 0x9E37_79B9_7F4A_7C15
            var z = state
            z = (z ^ (z >> 30)) &* 0xBF58_476D_1CE4_E5B9
            z = (z ^ (z >> 27)) &* 0x94D0_49BB_1331_11EB
            return z ^ (z >> 31)
        }
    }

    private static let words = [
        "parse", "cache", "graph", "layout", "render", "decode", "buffer", "stream",
        "handler", "service", "client", "worker", "queue", "index", "token", "session",
        "config", "schema", "cursor", "socket", "reader", "writer", "matcher", "builder"
    ]

    /// Builds and writes one corpus to a fresh temp directory. The caller owns cleanup
    /// (`FileManager.default.removeItem(at: fixture.rootDir)`).
    static func make(_ corpus: BenchCorpus) throws -> BenchFixture {
        var rng = SplitMix64(state: seed(for: corpus))
        let rootDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("contour-bench-\(corpus.rawValue)-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: rootDir, withIntermediateDirectories: true)

        var files: [String] = []
        var diff = ""
        var additions = 0

        func addFile(path: String, lines: Int) throws {
            files.append(path)
            let content = contentLines(count: lines, rng: &rng)
            diff += fileDiff(path: path, lines: content)
            additions += content.count
            try write(content, to: rootDir.appendingPathComponent(path))
        }

        for i in 0..<corpus.fileCount {
            try addFile(path: "src/\(word(&rng))/\(word(&rng))_\(i).rs", lines: corpus.linesPerFile)
        }
        if corpus.oversizedFileLines > 0 {
            try addFile(path: "src/generated/big_table.rs", lines: corpus.oversizedFileLines)
        }

        // Not a real git object id — offline bench mode never asks git to resolve it — just
        // a stable, corpus-distinct 40-character stand-in shaped like one.
        let sha = String(repeating: String(corpus.rawValue.first!), count: 40)
        let ctx = RawPRContext(
            url: "https://example.invalid/bench/\(corpus.rawValue)/pull/1",
            owner: "bench", repo: corpus.rawValue, number: 1,
            title: "Bench fixture: \(corpus.rawValue) PR (\(files.count) files)",
            body: "Synthetic fixture generated by BenchFixtures for issue #60's latency bench. Not a real change.",
            author: "bench-bot", state: "OPEN", headRefName: "bench/\(corpus.rawValue)", baseRefName: "main",
            headSha: sha, baseSha: String(repeating: "0", count: 40), isCrossRepository: false,
            headCloneURL: "https://example.invalid/bench/\(corpus.rawValue).git",
            additions: additions, deletions: 0, changedFiles: files.count, files: files,
            commits: [CommitInfo(sha: String(repeating: "1", count: 40), message: "Generate \(corpus.rawValue) fixture", author: "bench-bot")],
            comments: [], reviews: [], diff: diff
        )

        let checkout = RepoCheckout(rootDir: rootDir, headSha: ctx.headSha, baseSha: ctx.baseSha, symbolIndexPath: nil)
        return BenchFixture(context: ctx, checkout: checkout, rootDir: rootDir)
    }

    private static func seed(for corpus: BenchCorpus) -> UInt64 {
        switch corpus {
        case .small: return 0x5eed_0001
        case .medium: return 0x5eed_0002
        case .large: return 0x5eed_0003
        }
    }

    private static func word(_ rng: inout SplitMix64) -> String { words[Int(rng.next() % UInt64(words.count))] }

    // A plain loop, not `.map`: a closure can't capture its own enclosing `inout`
    // parameter, so `rng` has to be threaded through by hand here.
    private static func contentLines(count: Int, rng: inout SplitMix64) -> [String] {
        var lines: [String] = []
        lines.reserveCapacity(count)
        for i in 0..<count {
            lines.append("    let \(word(&rng))_\(i) = \(word(&rng))(\(rng.next() % 1000));")
        }
        return lines
    }

    /// One file's unified-diff hunk. Every generated line is an addition to a new file: the
    /// point isn't a realistic diff, it's a diff of the right *shape and size* for
    /// `UnifiedDiff.parse` and `PromptBuilder.contextFileContents` to do real, scaled work on.
    private static func fileDiff(path: String, lines: [String]) -> String {
        var out = "diff --git a/\(path) b/\(path)\n"
        out += "new file mode 100644\n"
        out += "--- /dev/null\n"
        out += "+++ b/\(path)\n"
        out += "@@ -0,0 +1,\(lines.count) @@\n"
        for line in lines { out += "+\(line)\n" }
        return out
    }

    private static func write(_ lines: [String], to url: URL) throws {
        try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
        try lines.joined(separator: "\n").write(to: url, atomically: true, encoding: .utf8)
    }
}
