import Foundation
@testable import Contour

enum BenchCorpus: String, CaseIterable {
    case small, medium, large

    var fileCount: Int {
        switch self {
        case .small: return 3
        case .medium: return 40
        case .large: return 300
        }
    }

    var linesPerFile: Int {
        switch self {
        case .small: return 20
        case .medium: return 60
        case .large: return 120
        }
    }

    var oversizedFileLines: Int {
        switch self {
        case .small, .medium: return 0
        case .large: return 30_000
        }
    }
}

struct BenchFixture {
    var context: RawPRContext
    var checkout: RepoCheckout
    var rootDir: URL
}

enum BenchFixtures {
    private struct SplitMix64: RandomNumberGenerator {
        var state: UInt64
        mutating func next() -> UInt64 {
            state &+= 0x9E37_79B9_7F4A_7C15
            var z = state
            z = (z ^ (z >> 30)) &* 0xBF58_476D_1CE4_E5B9
            z = (z ^ (z >> 27)) &* 0x94D0_49BB_1331_11EB
            return z ^ (z >> 31)
        }
    }

    private static let words = [
        "parse", "cache", "graph", "layout", "render", "decode", "buffer", "stream",
        "handler", "service", "client", "worker", "queue", "index", "token", "session",
        "config", "schema", "cursor", "socket", "reader", "writer", "matcher", "builder"
    ]

    static func make(_ corpus: BenchCorpus) throws -> BenchFixture {
        var rng = SplitMix64(state: seed(for: corpus))
        let rootDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("contour-bench-\(corpus.rawValue)-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: rootDir, withIntermediateDirectories: true)

        var files: [String] = []
        var diff = ""
        var additions = 0

        func addFile(path: String, lines: Int) throws {
            files.append(path)
            let content = contentLines(count: lines, rng: &rng)
            diff += fileDiff(path: path, lines: content)
            additions += content.count
            try write(content, to: rootDir.appendingPathComponent(path))
        }

        for i in 0..<corpus.fileCount {
            try addFile(path: "src/\(word(&rng))/\(word(&rng))_\(i).rs", lines: corpus.linesPerFile)
        }
        if corpus.oversizedFileLines > 0 {
            try addFile(path: "src/generated/big_table.rs", lines: corpus.oversizedFileLines)
        }

        let sha = String(repeating: String(corpus.rawValue.first!), count: 40)
        let ctx = RawPRContext(
            url: "https://example.invalid/bench/\(corpus.rawValue)/pull/1",
            owner: "bench", repo: corpus.rawValue, number: 1,
            title: "Bench fixture: \(corpus.rawValue) PR (\(files.count) files)",
            body: "Synthetic fixture generated by BenchFixtures for issue #60's latency bench. Not a real change.",
            author: "bench-bot", state: "OPEN", headRefName: "bench/\(corpus.rawValue)", baseRefName: "main",
            headSha: sha, baseSha: String(repeating: "0", count: 40), isCrossRepository: false,
            headCloneURL: "https://example.invalid/bench/\(corpus.rawValue).git",
            additions: additions, deletions: 0, changedFiles: files.count, files: files,
            commits: [CommitInfo(sha: String(repeating: "1", count: 40), message: "Generate \(corpus.rawValue) fixture", author: "bench-bot")],
            comments: [], reviews: [], diff: diff
        )

        let checkout = RepoCheckout(rootDir: rootDir, headSha: ctx.headSha, baseSha: ctx.baseSha, symbolIndexPath: nil)
        return BenchFixture(context: ctx, checkout: checkout, rootDir: rootDir)
    }

    private static func seed(for corpus: BenchCorpus) -> UInt64 {
        switch corpus {
        case .small: return 0x5eed_0001
        case .medium: return 0x5eed_0002
        case .large: return 0x5eed_0003
        }
    }

    private static func word(_ rng: inout SplitMix64) -> String { words[Int(rng.next() % UInt64(words.count))] }

    private static func contentLines(count: Int, rng: inout SplitMix64) -> [String] {
        var lines: [String] = []
        lines.reserveCapacity(count)
        for i in 0..<count {
            lines.append("    let \(word(&rng))_\(i) = \(word(&rng))(\(rng.next() % 1000));")
        }
        return lines
    }

    private static func fileDiff(path: String, lines: [String]) -> String {
        var out = "diff --git a/\(path) b/\(path)\n"
        out += "new file mode 100644\n"
        out += "--- /dev/null\n"
        out += "+++ b/\(path)\n"
        out += "@@ -0,0 +1,\(lines.count) @@\n"
        for line in lines { out += "+\(line)\n" }
        return out
    }

    private static func write(_ lines: [String], to url: URL) throws {
        try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
        try lines.joined(separator: "\n").write(to: url, atomically: true, encoding: .utf8)
    }
}
